// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9L4xXXnXwPa62ioA2LShQ-0RdAcbeotc',
    appId: '1:823307041176:web:ddaf3c80339832920653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    authDomain: 'codingwitht-c6d0f.firebaseapp.com',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    measurementId: 'G-GPNQNEKECP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdRjw0tdFdERdPZDoMagTbxPhSg368Zic',
    appId: '1:823307041176:android:892482637f44e4c10653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:cef880e79df81b420653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-qfcmju8p2mbqre4rl5kufhr7dhs9hs33.apps.googleusercontent.com',
    iosClientId: '823307041176-ao9frv5a25ebiimfstp79lnc214urhgj.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyypc4MyqBBneptEWpF17u3s7cu8X4wIY',
    appId: '1:823307041176:ios:3be076689b6866ea0653ed',
    messagingSenderId: '823307041176',
    projectId: 'codingwitht-c6d0f',
    storageBucket: 'codingwitht-c6d0f.appspot.com',
    androidClientId: '823307041176-qfcmju8p2mbqre4rl5kufhr7dhs9hs33.apps.googleusercontent.com',
    iosClientId: '823307041176-7pen3ehk09mbnp7ukg6lm4a9sgr80pjr.apps.googleusercontent.com',
    iosBundleId: 'com.example.cwtEcommerceApp.RunnerTests',
  );
}
